name: Open Issue on Staging Repo
on:
  push:
    branches: [ main ]

jobs:
  gitIssueCreation:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - name: Install GH Cli
        run: |
          brew install gh
      - name: Cli Login
        run: |         
          gh issue create --title "I found a bug" --body "Nothing works" -R microsoft/azuretipsandtricks-private
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT  }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_OWNER: 'microsoft'
          GITHUB_REPOSITORY: 'azuretipsandtricks-private'
          GITHUB_ISSUE_TITLE: 'Demo''ing Git Issue Creation'
          GITHUB_ISSUE_BODY: 'Demo''ing Git Issue Creation'
