name: Create PR
on: [pull_request]

jobs:
 gitIssueCreation:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo
      with:
        submodules: true
    - name: Install GH Cli
      run: |
        brew install gh
        
    - name: Clone Private repo
      run: |
        git clone "https://${{ secrets.PRIVATE_REPO_PAT  }}@github.com/microsoft/azuretipsandtricks-private.git" private
        cd private
        git checkout -b "${{ github.event.title }}"
        cp -R "${{ github.workspace }}/blog" "${{ github.workspace }}/private/src/blog"
        cp "${{ github.workspace }}/.vuepress/public/files"  "${{ github.workspace }}/src/.vuepress/public/file"
        git add .
        git commit -m "${{ github.event.title }}"
        git push origin "${{ github.event.titlee }}"
        
    - name: GH CLI
      run: |      
        cd private   
        gh pr create --title "${{ github.event.title }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT  }}
