name: Create PR
on: [pull_request]

jobs:
 gitIssueCreation:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Dump context
      uses: crazy-max/ghaction-dump-context@v1
        
        
    - uses: actions/checkout@v2
      name: Checkout Repo
      with:
        submodules: true
    - name: Install GH Cli
      run: |
        brew install gh
        
    - name: Clone Private repo
      run: |
        git clone "https://${{ secrets.PRIVATE_REPO_PAT  }}@github.com/microsoft/azuretipsandtricks-private.git" private
        cd private
        
        git config --global user.email "github-action@microsoft.com"
        git config --global user.name "GitHub Action"
        
        git fetch
        git pull
        git checkout -b "public-pr-${{ github.event.number }}"
        git push -u origin "public-pr-${{ github.event.number }}"
        
        cp -r "${{ github.workspace }}/blog" "${{ github.workspace }}/private/src/blog"
        cp -r "${{ github.workspace }}/.vuepress/public/files"  "${{ github.workspace }}/private/src/.vuepress/public/files"
                
        git add .
        git commit -m "${{ github.event.pull_request.title }}"
        git push
        
    - name: GH CLI
      run: |      
        cd "${{ github.workspace }}/private"   
        git checkout "public-pr-${{ github.event.number }}"
        COMMIT_MESSAGE="**Pull Request Created in public repo** <br /><br /> **Title:** ${{ github.event.pull_request.title }} <br /><br /> **Link:** https://github.com/microsoft/AzureTipsAndTricks/pull/${{ github.event.number }}"
        
        gh pr create --title "Public Repo PR" --body "$COMMIT_MESSAGE" -R microsoft/azuretipsandtricks-private
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT  }}
