name: Open Issue on Staging Repo
on:
  push:
    branches: [ main ]

jobs:
  gitIssueCreation:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - name: Install GH Cli
        run: |
          brew install gh
      - name: GH CLI
        run: |         
          echo "POST_COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B)" >> $GITHUB_ENV
          gh issue create --title "Update Made in Public Repo" --body "test" -R microsoft/azuretipsandtricks-private

        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT  }}
          GITHUB_SHA: ${{ github.sha }}
