name: Create PR
on: [pull_request]

jobs:
 gitIssueCreation:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo
      with:
        submodules: true
    - name: Install GH Cli
      run: |
        brew install gh
        
    - name: Clone Private repo
      run: |
        git clone https://github.com/microsoft/azuretipsandtricks-private.git private
        Username: "GitHub Action"
        Password: ${{ secrets.PRIVATE_REPO_PAT  }}
        cd private
        git checkout -b ${{ github.context.payload.pull_request.title }}
        cp -R "${{ github.workspace }}/blog" "${{ github.workspace }}/private/src/blog"
        cp "${{ github.workspace }}/.vuepress/public/files"  "${{ github.workspace }}/src/.vuepress/public/file"
        git add .
        git commit -m "${{ github.context.payload.pull_request.title }}"
        git push origin ${{ github.context.payload.pull_request.title }}
        
    - name: GH CLI
      run: |      
        cd private   
        gh pr create --title "${{ github.context.payload.pull_request.title }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT  }}
