name: Create PR
on: [pull_request]

jobs:
 gitIssueCreation:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Dump context
      uses: crazy-max/ghaction-dump-context@v1
        
        
    - uses: actions/checkout@v2
      name: Checkout Repo
      with:
        submodules: true
    - name: Install GH Cli
      run: |
        brew install gh
        
    - name: Clone Private repo
      run: |
        git clone "https://${{ secrets.PRIVATE_REPO_PAT  }}@github.com/microsoft/azuretipsandtricks-private.git" private
        cd private
        git fetch
        git pull
        git checkout -b "pr-${{ github.event.number }}"
        cp -r "${{ github.workspace }}/blog" "${{ github.workspace }}/private/src/blog"
        cp -r "${{ github.workspace }}/.vuepress/public/files"  "${{ github.workspace }}/private/src/.vuepress/public/files"
        
        git config --global user.email "github-action@microsoft.com"
        git config --global user.name "GitHub Action"
        
        git add .
        git commit -m "${{ github.event.pull_request.title }}"
        git push -u origin "pr-${{ github.event.number }}"
        
    - name: GH CLI
      run: |      
        cd private   
        gh pr create --title "${{ github.event.pull_request.title }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT  }}
